var lang_packs = {
  zh:{
    title: 'ZFS时间穿梭机控制台{0}',
    brname: '分支',
    orig: '基于',
    snpname: '快照',
    creation: '创建时间',
    svg: '显示时间树',
    note: '显示快照笔记',
    connection_error: '连接失败！请刷新页面。',
    in_use: '"{0}"还在使用连接。如果该窗口已关闭，请等几秒钟再试。',
    // https://stackoverflow.com/questions/1357078/whats-the-difference-between-nbsp-and/1357163#1357163
    step1_instr: ['第1步： 选择系统目标快照。请用左栏选择分支，用中栏选择该分支下的快照。 彩色标记释义：{0}，{1}，{2}，{3}',
		  '\u00a0\u00a0\u00a0当前分支\u00a0\u00a0\u00a0',
		  '\u00a0\u00a0\u00a0当前快照\u00a0\u00a0\u00a0',
		  '\u00a0\u00a0\u00a0目标分支\u00a0\u00a0\u00a0',
		  '\u00a0\u00a0\u00a0目标快照\u00a0\u00a0\u00a0'],
    step2_instr: ['第2步： 选择"/home"目标快照。请用左栏选择分支，用中栏选择该分支下的快照。 彩色标记释义：{0},{2},{3}',
		  '\u00a0\u00a0\u00a0当前分支\u00a0\u00a0\u00a0',
		  '',
		  '\u00a0\u00a0\u00a0目标分支\u00a0\u00a0\u00a0',
		  '\u00a0\u00a0\u00a0目标快照\u00a0\u00a0\u00a0'],
    go_back: '上一步',
    go_forward: '下一步',
    illegal_branch: '是当前分支。请选择另一个分支。',
    confirm: '已选定：\n系统目标快照{step1snp}(创建于{step1time})\n"/home"目标快照{step2snp}(创建于{step2time})\n\n确定要继续？',
    revert: '恢复至选定目标快照',
    wait: '请稍候...',
    success: '操作成功！',
    fail: '操作失败！',
    restart: '再来一次',
    reboot: '重启电脑',
    rebooting: '重启进行中，请稍候...',
    not_rebooting: '重启失败！',
    no_note: '没有快照笔记。'
  },
  en: {
    title: 'ZFS Time Shuttle Console {0}',
    brname: 'Branch',
    orig: 'Based on',
    snpname: 'Snapshot',
    creation: 'Created at',
    svg: 'Display Time Tree',
    note: 'Display Notes',
    connection_error: 'Connection error! Please refresh the page.',
    in_use: '"{0}" is still using the connection. If the tab is already closed, please wait for a few seconds and try again.',
    step1_instr: ['Step 1: choose the target snapshot for system. Color code: {0}, {1}, {2}, {3}',
		  'current branch',
		  'current snapshot',
		  'target branch',
		  'target snapshot'],
    step2_instr: ['Step 2: choose the target snapshot for "/home". Color code: {0}, {2}, {3}',
		  'current branch',
		  '',
		  'target branch',
		  'target snapshot'],
    go_back: '<Back',
    go_forward: 'Next>',
    illegal_branch: ' is the current branch. Please choose a different branch!',
    confirm: 'Chosen:\nsystem target snapshot {step1snp} (created at {step1time})\n"/home" target snapshot {step2snp} (created at {step2time})\n\nWould you like to continue?',
    revert: 'Revert to Target Snapshots',
    wait: 'Please wait ...',
    success: 'Success!',
    fail: 'Fail!',
    restart: 'Start Over',
    reboot: 'Reboot',
    rebooting: 'Rebooting started. Please wait...',
    not_rebooting: 'Failed to reboot!',
    no_note: ' doesn\'t have notes.'
  }
};
